project:
  type: website
  output-dir: docs

website:
  title: "Applied Econometrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Recitations
        menu: 
          - recitations/recitation-1.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



